provider:
  name: faas
  gateway: http://srv.locational.io:8080
functions:
  faas-template-r-fn:
    lang: dockerfile
    handler: ./fn-dbscan-clusterer
    image: locational/fn-dbscan-clusterer:latest
