provider:
  name: openfaas
  gateway: https://faas.srv.disarm.io
functions:
  fn-dbscan-clusterer:
    lang: r-geospatial
    handler: ./function
    image: disarm/fn-dbscan-clusterer:0.2.0
    environment:
      exec_timeout: 900
      write_timeout: 900
      read_timeout: 900
      combine_output: false
      # write_debug: true
    labels:
      com.openfaas.scale.zero: true
