provider:
  name: faas
  gateway: http://faas.srv.disarm.io
functions:
  fn-dbscan-clusterer-0-0-1:
    lang: dockerfile
    handler: ./fn-dbscan-clusterer
    image: disarm/fn-dbscan-clusterer:0.0.1
    environment:
      write_timeout: 60
      read_timeout: 60
      combine_output: false