provider:
  name: faas
  gateway: http://faas.srv.disarm.io
functions:
  fn-dbscan-clusterer:
    lang: dockerfile
    handler: ./fn-dbscan-clusterer
    image: disarm/fn-dbscan-clusterer:latest
    environment:
      write_debug: true
      write_timeout: 60
      combine_output: false